import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';

const base=process.env.BASE_URL||'http://localhost:3017';
const browser=await chromium.launch({channel:'chrome',headless:true});
const errors=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'no-preference'});
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base);
 await expect(page.locator('html')).toHaveClass(/motion-ready/);
 const scene=page.locator('.process-gallery');
 const cards=scene.locator('.process-card');
 await expect(cards).toHaveCount(4);
 await expect(cards.nth(1)).toHaveClass(/is-selected/);
 const width=await cards.nth(0).evaluate(e=>e.getBoundingClientRect().width);
 await scene.hover({position:{x:70,y:140}});
 await expect(cards.nth(0)).toHaveClass(/is-selected/);
 await expect.poll(()=>cards.nth(0).evaluate(e=>e.getBoundingClientRect().width)).toBeGreaterThan(width*1.5);
 await scene.hover({position:{x:90,y:150}});
 await expect.poll(()=>scene.evaluate(e=>e.style.getPropertyValue('--pointer-x'))).not.toBe('');
 await cards.nth(1).hover();
 await expect(cards.nth(1)).toHaveClass(/is-selected/);
 // The panels sit with the method, below the fold: settle the scroll before measuring.
 await scene.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));
 const box=await scene.boundingBox();
 await page.mouse.move(box.x+50,box.y+120);
 await page.mouse.down();
 await expect(scene).toHaveClass(/is-dragging/);
 await page.mouse.move(box.x+box.width-30,box.y+120,{steps:8});
 await expect(cards.nth(3)).toHaveClass(/is-selected/);
 await page.mouse.up();
 await expect(scene).not.toHaveClass(/is-dragging/);
 assert.equal(await scene.evaluate(e=>getComputedStyle(e).touchAction),'pan-y');
 await page.mouse.move(0,0);
 await expect.poll(()=>scene.evaluate(e=>e.style.getPropertyValue('--pointer-x'))).toBe('');
 await page.emulateMedia({reducedMotion:'reduce'});
 await expect(page.locator('html')).not.toHaveClass(/motion-ready/);
 assert.equal(await cards.nth(0).evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
 await scene.hover({position:{x:70,y:140}});
 await expect(cards.nth(3)).toHaveClass(/is-selected/);
 assert.equal(await scene.evaluate(e=>e.style.getPropertyValue('--pointer-x')),'');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await scene.hover({position:{x:100,y:140}});
 await expect(cards.nth(0)).toHaveClass(/is-selected/);
 await page.goto(base+'/fr/lab');
 await page.locator('.lab-card').first().scrollIntoViewIfNeeded();
 await expect(page.locator('.lab-card').first()).toHaveClass(/has-entered/);
 assert.equal(await page.locator('.lab-product-object img').count(),0);
 await expect(page.locator('.brand-preview')).toBeVisible();
 await page.locator('.lab-card').first().focus();
 assert.equal(await page.locator('.lab-card').first().evaluate(e=>getComputedStyle(e).outlineStyle),'solid');
 await page.goto(base+'/fr/lab/the-brief-before-the-brief');
 const field=page.locator('.brief-form textarea').first();
 await field.fill('Clarifier une direction');
 await expect(field).toHaveAttribute('data-filled','true');
 await field.fill('');
 await expect(field).toHaveAttribute('data-filled','false');
 const context=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
 const plain=await context.newPage();
 for(const route of ['/','/fr','/lab','/fr/lab','/practice','/fr/practice','/thinking','/fr/about']){
  assert.equal((await plain.goto(base+route)).status(),200);
  assert.equal(await plain.locator('h1').evaluate(e=>getComputedStyle(e).opacity),'1');
  assert.equal(await plain.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,route+' JS-off overflow');
  assert.equal(await plain.locator('main').isVisible(),true);
  assert.equal(await plain.locator('img[src*="quantum-aperture"],img[src$="compass.svg"],img[src$="mark.svg"]').count(),0);
 }
 await context.close();
 const touchContext=await browser.newContext({hasTouch:true,isMobile:true,viewport:{width:390,height:844},reducedMotion:'no-preference'});
 const touch=await touchContext.newPage();
 touch.on('pageerror',error=>errors.push(error.message));
 await touch.goto(base+'/fr');
 const panels=touch.locator('.process-card');
 await panels.nth(0).tap();
 await expect(panels.nth(0)).toHaveClass(/is-selected/);
 await panels.nth(1).tap();
 await expect(panels.nth(1)).toHaveClass(/is-selected/);
 await expect(touch.locator('.process-gallery')).not.toHaveClass(/is-dragging/);
 await touchContext.close();
 assert.deepEqual(errors,[]);
 console.log('PASS: panels expand on hover and drag; release resets; native vertical touch scrolling; reduced-motion switching; Lab keyboard focus; form feedback; 8 readable JS-off routes.');
} finally {await browser.close()}
